routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\UsersController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\SupplierController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('login');
    // return view('welcome');
});

Auth::routes();

Route::group(['middleware' => ['auth']], function () {
    Route::get('/home', [HomeController::class, 'index'])->name('home');
    Route::resource('users', UsersController::class);
    Route::group(['middleware' => ['IsAdmin']], function () {
        Route::resource('suppliers', SupplierController::class);
    });
});

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'role',
        'email_verified_at',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function company()
    {
        // return $this->hasOne(Company::class);
        // return $this->embedsOne(Company::class);
    }
}

app/Http/Controllers/Api/UsersController.php
<?php

namespace App\Http\Controllers\Api;

use App\Models\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Resources\UserResource;
use App\Http\Resources\UserCollection;
use Illuminate\Support\Facades\Artisan;
use App\Http\Requests\users\UpdateRequest;

class UsersController extends Controller
{
    public function index(Request $request)
    {
        $query = User::query();

        if ($request->filled('search')) {
            $search = $request->search;
            $query->where(function ($query) use ($search) {
                $query->where('name', 'like', '%' . $search . '%');
            });
        }

        // if ($request->filled('staff')) {
        //     $query->where('type', 'Staff');
        // }

        if ($request->filled('perPage')) {
            $per_page = $request->perPage;
            $users = $query->paginate((int) $per_page);
            return  new UserCollection($users);
        }

        return  UserResource::collection($query->get());
    }

    public function update(UpdateRequest $request, User $user)
    {
        $user->update(array_merge(
            $request->validated(),
            [
                'active' => (int) $request->active
            ]
        ));
        return response()->json(null, 200);
    }

    public function destroy(User $user)
    {
        $user->delete();
        return response()->json(null, 204);
    }
}

app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Session;
use App\Http\Requests\users\CreateRequest;
use App\Http\Requests\users\UpdateRequest;

class UsersController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $this->authorize('viewAny', Auth::user());
        return view('users.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('users.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateRequest $request)
    {
        User::create(
            array_merge(
                $request->validated(),
                [
                    'active' => (int) $request->active,
                    'type' => 'Staff',
                    'password' => Hash::make($request->password)
                ]
            )
        );

        Session::flash('message', "User Saved");
        return redirect(route('users.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        $this->authorize('update', $user);
        if (empty($user)) {
            Session::flash('message', "User Not Found");
            return redirect(route('users.index'));
        }

        return view('users.edit', compact(['user']));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateRequest $request, User $user)
    {
        $this->authorize('update', $user);
        if (empty($user)) {
            Session::flash('message', "User Not Found");
            return redirect(route('users.index'));
        }
        $user->update(
            array_merge(
                $request->validated(),
                [
                    'active' => (int) $request->active
                ]
            )
        );
        Session::flash('message', "User Updated");
        return redirect(route('users.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        //
    }
}

app/View/Components/users/fields.php
<?php

namespace App\View\Components\users;

use App\Models\Supplier;
use Illuminate\View\Component;

class fields extends Component
{
    public $supplier;

    /**
     * Create a new component instance.
     *
     * @return void
     */
    public function __construct(Supplier $supplier = null)
    {
        $this->supplier = $supplier;
    }

    /**
     * Get the view / contents that represent the component.
     *
     * @return \Illuminate\Contracts\View\View|\Closure|string
     */
    public function render()
    {
        return view('components.suppliers.fields');
    }
}

resources/views/users/create.blade.php
<x-layouts.authenticated title="Users" active-page="users">
    <div class="main-container">
        <div class="page-header">
            <ol class="breadcrumb">
                <li class="breadcrumb-item">Users</li>
                <li class="breadcrumb-item active">Create</li>
            </ol>
            <ul class="app-actions">
                <li>
                    <a href="#" id="reportrange">
                        <span class="range-text">Sep 8, 2022 - Oct 7, 2022</span>
                        <i class="icon-chevron-down"></i>
                    </a>
                </li>
                <li>
                    <a href="#" data-toggle="tooltip" data-placement="top" title=""
                        data-original-title="Print">
                        <i class="icon-print"></i>
                    </a>
                </li>
                <li>
                    <a href="#" data-toggle="tooltip" data-placement="top" title=""
                        data-original-title="Download CSV">
                        <i class="icon-cloud_download"></i>
                    </a>
                </li>
            </ul>
        </div>
        <div class="content-wrapper">
            <div class="row justify-content-center gutters">
                <div class="col-xl-10 col-lg-10 col-md-12 col-sm-12 col-12">
                    <form id="user-form" method="POST" action="{{ route('users.store') }}" novalidate>
                        @csrf
                        <div class="card m-0">
                            <div class="card-header">
                                <div class="card-title">New User</div>
                            </div>
                            <div class="card-body">
                                <div class="row gutters">
                                    <x-users.fields />
                                </div>
                                <div class="row gutters">
                                    <div class="col-xl-12">
                                        <button id="submit" type="submit" class="btn btn-primary float-right">
                                            Save
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    @push('scripts')
        <script>
            const userForm = document.getElementById('user-form');
            const name = document.getElementById('name');
            const email = document.getElementById('email');
            const password = document.getElementById('password');
            const password_confirmation = document.getElementById('password_confirmation');
            const country_code = document.getElementById('country_code');
            const phone = document.getElementById('phone');
            const company_name = document.getElementById('company_name');

            userForm.addEventListener('submit', (event) => {
                if (validate()) {
                    console.log("Form submitting");
                    userForm.submit();
                    return;
                }
                event.preventDefault();
            });

            function clearClasses() {
                name.classList.remove("is-invalid");
                email.classList.remove("is-invalid");
                password.classList.remove("is-invalid");
                password_confirmation.classList.remove("is-invalid");
                country_code.classList.remove("is-invalid");
                phone.classList.remove("is-invalid");
                company_name.classList.remove("is-invalid");
            }

            function validate() {
                clearClasses();
                let isValid = true;
                if (name.value === '') {
                    name.classList.add("is-invalid")
                    isValid = false;
                }
                if (email.value === '') {
                    email.classList.add("is-invalid")
                    isValid = false;
                }
                if (password.value === '') {
                    password.classList.add("is-invalid")
                    isValid = false;
                }
                if (password_confirmation.value === '') {
                    password_confirmation.classList.add("is-invalid")
                    isValid = false;
                }
                if (country_code.value === '') {
                    country_code.classList.add("is-invalid")
                    isValid = false;
                }
                if (phone.value === '') {
                    phone.classList.add("is-invalid")
                    isValid = false;
                }
                if (company_name.value === '') {
                    company_name.classList.add("is-invalid")
                    isValid = false;
                }
                return isValid;
            }
        </script>
    @endpush
</x-layouts.authenticated>

resources/views/users/edit.blade.php
<x-layouts.authenticated title="Users" active-page="users">
    <div class="main-container">
        <div class="page-header">
            <ol class="breadcrumb">
                <li class="breadcrumb-item">Users</li>
                <li class="breadcrumb-item active">Edit</li>
            </ol>
            <ul class="app-actions">
                <li>
                    <a href="#" id="reportrange">
                        <span class="range-text">Sep 8, 2022 - Oct 7, 2022</span>
                        <i class="icon-chevron-down"></i>
                    </a>
                </li>
                <li>
                    <a href="#" data-toggle="tooltip" data-placement="top" title=""
                        data-original-title="Print">
                        <i class="icon-print"></i>
                    </a>
                </li>
                <li>
                    <a href="#" data-toggle="tooltip" data-placement="top" title=""
                        data-original-title="Download CSV">
                        <i class="icon-cloud_download"></i>
                    </a>
                </li>
            </ul>
        </div>
        <div class="content-wrapper">
            <div class="row justify-content-center gutters">
                <div class="col-xl-10 col-lg-10 col-md-12 col-sm-12 col-12">
                    <form id="user-form" method="POST" action="{{ route('users.update', $user->id) }}" novalidate>
                        @method('PUT')
                        @csrf
                        <div class="card m-0">
                            <div class="card-header">
                                <div class="card-title">New User</div>
                            </div>
                            <div class="card-body">
                                <div class="row gutters">
                                    <x-users.fields :user="$user" />
                                </div>
                                <div class="row gutters">
                                    <div class="col-xl-12">
                                        <button id="submit" type="submit" class="btn btn-primary float-right">
                                            Update
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    @push('scripts')
        <script>
            const userForm = document.getElementById('user-form');
            const name = document.getElementById('name');
            const email = document.getElementById('email');
            const country_code = document.getElementById('country_code');
            const phone = document.getElementById('phone');
            const company_name = document.getElementById('company_name');

            userForm.addEventListener('submit', (event) => {
                if (validate()) {
                    console.log("Form submitting");
                    userForm.submit();
                    return;
                }
                event.preventDefault();
            });

            function clearClasses() {
                name.classList.remove("is-invalid");
                email.classList.remove("is-invalid");
                country_code.classList.remove("is-invalid");
                phone.classList.remove("is-invalid");
                company_name.classList.remove("is-invalid");
            }

            function validate() {
                console.log('validate');
                clearClasses();
                let isValid = true;
                console.log('name.value');
                console.log(name.value);
                if (name.value === '') {
                    name.classList.add("is-invalid")
                    isValid = false;
                }
                if (email.value === '') {
                    email.classList.add("is-invalid")
                    isValid = false;
                }
                if (country_code.value === '') {
                    country_code.classList.add("is-invalid")
                    isValid = false;
                }
                if (phone.value === '') {
                    phone.classList.add("is-invalid")
                    isValid = false;
                }
                if (company_name.value === '') {
                    company_name.classList.add("is-invalid")
                    isValid = false;
                }
                return isValid;
            }
        </script>
    @endpush
</x-layouts.authenticated>

resources/views/users/index.blade.php
<x-layouts.authenticated title="Users" active-page="users">
    @push('css')
        <link rel="stylesheet" href="/topbar/vendor/datatables/dataTables.bs4.css" />
        <link rel="stylesheet" href="/topbar/vendor/datatables/dataTables.bs4-custom.css" />
    @endpush

    <div class="main-container">
        <div class="page-header">
            <ol class="breadcrumb">
                <li class="breadcrumb-item">Tables</li>
                <li class="breadcrumb-item active">Data Tables</li>
            </ol>

            <ul class="app-actions">
                <li>
                    <a href="#" id="reportrange">
                        <span class="range-text">Sep 7, 2022 - Oct 6, 2022</span>
                        <i class="icon-chevron-down"></i>
                    </a>
                </li>
                <li>
                    <a href="#" data-toggle="tooltip" data-placement="top" title=""
                        data-original-title="Print">
                        <i class="icon-print"></i>
                    </a>
                </li>
                <li>
                    <a href="#" data-toggle="tooltip" data-placement="top" title=""
                        data-original-title="Download CSV">
                        <i class="icon-cloud_download"></i>
                    </a>
                </li>
            </ul>
        </div>
        <div class="content-wrapper">
            <div class="row gutters">
                <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">

                    <div class="table-container" id="app">
                        <div class="t-header">
                            <p>Users</p>
                            <a href="{{ route('users.create') }}" class="btn btn-primary btn-lg">
                                Add New
                                User
                            </a>
                        </div>
                        <users-index></users-index>
                    </div>
                </div>
            </div>
        </div>
    </div>

    @push('scripts')
        @vite('resources/js/app.js')
    @endpush
</x-layouts.authenticated>