routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\UsersController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\SupplierController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('login');
    // return view('welcome');
});

Auth::routes();

Route::group(['middleware' => ['auth']], function () {
    Route::get('/home', [HomeController::class, 'index'])->name('home');
    Route::resource('users', UsersController::class);
    Route::group(['middleware' => ['IsAdmin']], function () {
        Route::resource('suppliers', SupplierController::class);
    });
});

app/Models/Supplier.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Supplier extends Model
{
    use HasFactory;

    public $fillable = [
        'name',
        'email',
        'mobile_phone',
        'address'
    ];
}

app/Http/Controllers/Api/SuppliersController.php
<?php

namespace App\Http\Controllers\Api;

use App\Models\User;
use App\Models\Supplier;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Resources\UserResource;
use App\Http\Resources\UserCollection;
use Illuminate\Support\Facades\Artisan;
use App\Http\Resources\SupplierResource;
use App\Http\Resources\SupplierCollection;
use App\Http\Requests\suppliers\UpdateRequest;

class SuppliersController extends Controller
{
    public function index(Request $request)
    {
        $query = Supplier::query();

        if ($request->filled('search')) {
            $search = $request->search;
            $query->where(function ($query) use ($search) {
                $query->where('name', 'like', '%' . $search . '%');
            });
        }

        if ($request->filled('perPage')) {
            $per_page = $request->perPage;
            $users = $query->paginate((int) $per_page);
            return  new SupplierCollection($users);
        }

        return  SupplierResource::collection($query->get());
    }

    public function update(UpdateRequest $request, Supplier $supplier)
    {
        $supplier->update($request->validated());
        return response()->json(null, 200);
    }

    public function destroy(Supplier $supplier)
    {
        $supplier->delete();
        return response()->json(null, 204);
    }
}

app/Http/Controllers/SupplierController.php
<?php

namespace App\Http\Controllers;

use App\Models\Supplier;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Session;
use App\Http\Requests\suppliers\CreateRequest;
use App\Http\Requests\suppliers\UpdateRequest;

class SupplierController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('suppliers.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('suppliers.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateRequest $request)
    {
        Supplier::create(
            $request->validated()
        );
        Session::flash('message', "Supplier Saved");
        return redirect(route('suppliers.index'));
    }

    public function show(Supplier $supplier)
    {
        //
    }

    public function edit(Supplier $supplier)
    {
        if (empty($supplier)) {
            return redirect(route('suppliers.index'));
        }

        return view('suppliers.edit', compact(['supplier']));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateRequest $request, Supplier $supplier)
    {
        if (empty($supplier)) {
            Session::flash('message', "Supplier Not Found");
            return redirect(route('suppliers.index'));
        }
        $supplier->update(
            $request->validated(),
        );
        Session::flash('message', "Supplier Updated");
        return redirect(route('suppliers.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        //
    }
}

app/View/Components/suppliers/fields.php
<?php

namespace App\View\Components\suppliers;

use App\Models\User;
use Illuminate\View\Component;

class fields extends Component
{
    public $user;

    /**
     * Create a new component instance.
     *
     * @return void
     */
    public function __construct(User $user = null)
    {
        $this->user = $user;
    }

    /**
     * Get the view / contents that represent the component.
     *
     * @return \Illuminate\Contracts\View\View|\Closure|string
     */
    public function render()
    {
        return view('components.users.fields');
    }
}

resources/views/suppliers/create.blade.php
<x-layouts.authenticated title="Suppliers" active-page="suppliers">
    <div class="main-container">
        <div class="page-header">
            <ol class="breadcrumb">
                <li class="breadcrumb-item">Suppliers</li>
                <li class="breadcrumb-item active">Create</li>
            </ol>
            <ul class="app-actions">
                <li>
                    <a href="#" id="reportrange">
                        <span class="range-text">Sep 8, 2022 - Oct 7, 2022</span>
                        <i class="icon-chevron-down"></i>
                    </a>
                </li>
                <li>
                    <a href="#" data-toggle="tooltip" data-placement="top" title=""
                        data-original-title="Print">
                        <i class="icon-print"></i>
                    </a>
                </li>
                <li>
                    <a href="#" data-toggle="tooltip" data-placement="top" title=""
                        data-original-title="Download CSV">
                        <i class="icon-cloud_download"></i>
                    </a>
                </li>
            </ul>
        </div>
        <div class="content-wrapper">
            <div class="row justify-content-center gutters">
                <div class="col-xl-10 col-lg-10 col-md-12 col-sm-12 col-12">
                    <form id="supplier-form" method="POST" action="{{ route('suppliers.store') }}" novalidate>
                        @csrf
                        <div class="card m-0">
                            <div class="card-header">
                                <div class="card-title">New Supplier</div>
                            </div>
                            <div class="card-body">
                                <div class="row gutters">
                                    <x-suppliers.fields :supplier="null" />
                                </div>
                                <div class="row gutters">
                                    <div class="col-xl-12">
                                        <button id="submit" type="submit" class="btn btn-primary float-right">
                                            Save
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    @push('scripts')
        <script>
            const supplierForm = document.getElementById('supplier-form');
            const name = document.getElementById('name');
            const email = document.getElementById('email');
            const mobile_phone = document.getElementById('mobile_phone');

            supplierForm.addEventListener('submit', (event) => {
                if (validate()) {
                    supplierForm.submit();
                    return;
                }
                event.preventDefault();
            });

            function clearClasses() {
                name.classList.remove("is-invalid");
                email.classList.remove("is-invalid");
                mobile_phone.classList.remove("is-invalid");
            }

            function validate() {
                clearClasses();
                let isValid = true;
                if (name.value === '') {
                    name.classList.add("is-invalid")
                    isValid = false;
                }
                if (email.value === '') {
                    email.classList.add("is-invalid")
                    isValid = false;
                }
                if (mobile_phone.value === '') {
                    mobile_phone.classList.add("is-invalid")
                    isValid = false;
                }
                return isValid;
            }
        </script>
    @endpush
</x-layouts.authenticated>

resources/views/suppliers/edit.blade.php
<x-layouts.authenticated title="Suppliers" active-page="suppliers">
    <div class="main-container">
        <div class="page-header">
            <ol class="breadcrumb">
                <li class="breadcrumb-item">Suppliers</li>
                <li class="breadcrumb-item active">Edit</li>
            </ol>
            <ul class="app-actions">
                <li>
                    <a href="#" id="reportrange">
                        <span class="range-text">Sep 8, 2022 - Oct 7, 2022</span>
                        <i class="icon-chevron-down"></i>
                    </a>
                </li>
                <li>
                    <a href="#" data-toggle="tooltip" data-placement="top" title=""
                        data-original-title="Print">
                        <i class="icon-print"></i>
                    </a>
                </li>
                <li>
                    <a href="#" data-toggle="tooltip" data-placement="top" title=""
                        data-original-title="Download CSV">
                        <i class="icon-cloud_download"></i>
                    </a>
                </li>
            </ul>
        </div>
        <div class="content-wrapper">
            <div class="row justify-content-center gutters">
                <div class="col-xl-10 col-lg-10 col-md-12 col-sm-12 col-12">
                    <form id="supplier-form" method="POST" action="{{ route('suppliers.update', $supplier->id) }}"
                        novalidate>
                        @method('PUT')
                        @csrf
                        <div class="card m-0">
                            <div class="card-header">
                                <div class="card-title">New Supplier</div>
                            </div>
                            <div class="card-body">
                                <div class="row gutters">
                                    <x-suppliers.fields :supplier="$supplier" />
                                </div>
                                <div class="row gutters">
                                    <div class="col-xl-12">
                                        <button id="submit" type="submit" class="btn btn-primary float-right">
                                            Update
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    @push('scripts')
        <script>
            const supplierForm = document.getElementById('supplier-form');
            const name = document.getElementById('name');
            const email = document.getElementById('email');
            const mobile_phone = document.getElementById('mobile_phone');

            supplierForm.addEventListener('submit', (event) => {
                if (validate()) {
                    supplierForm.submit();
                    return;
                }
                event.preventDefault();
            });

            function clearClasses() {
                name.classList.remove("is-invalid");
                email.classList.remove("is-invalid");
                mobile_phone.classList.remove("is-invalid");
            }

            function validate() {
                clearClasses();
                let isValid = true;
                if (name.value === '') {
                    name.classList.add("is-invalid")
                    isValid = false;
                }
                if (email.value === '') {
                    email.classList.add("is-invalid")
                    isValid = false;
                }
                if (mobile_phone.value === '') {
                    mobile_phone.classList.add("is-invalid")
                    isValid = false;
                }
                return isValid;
            }
        </script>
    @endpush
</x-layouts.authenticated>

resources/views/suppliers/index.blade.php
<x-layouts.authenticated title="Suppliers" active-page="suppliers">
    @push('css')
        <link rel="stylesheet" href="/topbar/vendor/datatables/dataTables.bs4.css" />
        <link rel="stylesheet" href="/topbar/vendor/datatables/dataTables.bs4-custom.css" />
    @endpush

    <div class="main-container">
        <div class="page-header">
            <ol class="breadcrumb">
                <li class="breadcrumb-item">Tables</li>
                <li class="breadcrumb-item active">Data Tables</li>
            </ol>

            <ul class="app-actions">
                <li>
                    <a href="#" id="reportrange">
                        <span class="range-text">Sep 7, 2022 - Oct 6, 2022</span>
                        <i class="icon-chevron-down"></i>
                    </a>
                </li>
                <li>
                    <a href="#" data-toggle="tooltip" data-placement="top" title=""
                        data-original-title="Print">
                        <i class="icon-print"></i>
                    </a>
                </li>
                <li>
                    <a href="#" data-toggle="tooltip" data-placement="top" title=""
                        data-original-title="Download CSV">
                        <i class="icon-cloud_download"></i>
                    </a>
                </li>
            </ul>
        </div>
        <div class="content-wrapper">
            <div class="row gutters">
                <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">

                    <div class="table-container" id="app">
                        <div class="t-header">
                            <p>Supplier</p>
                            <a href="{{ route('suppliers.create') }}" class="btn btn-primary btn-lg">
                                Add New
                                Supplier
                            </a>
                        </div>
                        <suppliers-index></suppliers-index>
                    </div>
                </div>
            </div>
        </div>
    </div>

    @push('scripts')
        @vite('resources/js/app.js')
    @endpush
</x-layouts.authenticated>